function weekBookings(offset){const [m]=weekRange(offset),end=new Date(m);end.setDate(m.getDate()+5);const out=[];for(const [k,a] of Object.entries(data.bookings)){const [ds,h]=k.split('|'),d=parseDate(ds);if(d>=m&&d<end)out.push({date:ds,hour:+h,...a})}return out}
function renderReports(){const [m,f]=weekRange(reportOffset);$('reportWeekLabel').textContent=`${fmtLong(m)} – ${fmtLong(f)}`;const all=weekBookings(reportOffset);const total=all.length,seen=all.filter(x=>x.status==='seen').length,cancel=all.filter(x=>x.status==='cancelled').length,absence=all.filter(x=>x.status==='absence').length;$('reportKpis').innerHTML=`<div class="kpi"><b>${total}</b><span>Agendados</span></div><div class="kpi"><b>${seen}</b><span>Vistos</span></div><div class="kpi"><b>${cancel}</b><span>Cancelados</span></div><div class="kpi"><b>${absence}</b><span>Ausencias</span></div>`;let cards='';for(const p of PROFESSIONALS){const arr=all.filter(x=>x.professional===p.name),s=arr.filter(x=>x.status==='seen').length,c=arr.filter(x=>x.status==='cancelled').length,a=arr.filter(x=>x.status==='absence').length;const subject=`Psycast · Informe semanal ${fmtLong(m)} - ${fmtLong(f)}`;const body=`Hola ${p.name},\n\nInforme semanal de Psycast:\nAgendados: ${arr.length}\nVistos: ${s}\nCancelados: ${c}\nAusencias: ${a}\n\nDetalle:\n`+arr.sort((x,y)=>x.date.localeCompare(y.date)||x.hour-y.hour).map(x=>`${x.date} ${pad(x.hour)}:00 · ${x.initials||'—'} · ${statusText(x.status)}`).join('\n');const href=`mailto:${encodeURIComponent(p.email)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;cards+=`<div class="card report-card" style="--pc:${p.color}"><h3>${esc(p.name)}</h3><div class="email">${esc(p.email)}</div><div class="report-line"><span>Agendados</span><b>${arr.length}</b></div><div class="report-line"><span>Vistos</span><b>${s}</b></div><div class="report-line"><span>Cancelados</span><b>${c}</b></div><div class="report-line"><span>Ausencias</span><b>${a}</b></div><p><a class="btn" style="display:inline-block;text-decoration:none" href="${href}">Enviar por email</a></p></div>`}$('reportCards').innerHTML=cards}
function renderDonations(){if(!$('donationMonth').value){const n=new Date();$('donationMonth').value=`${n.getFullYear()}-${pad(n.getMonth()+1)}`}$('donationRate').value=data.donationRate??0;const month=$('donationMonth').value,rate=Number(data.donationRate||0);let rows='';for(const p of PROFESSIONALS){const count=Object.entries(data.bookings).filter(([k,a])=>k.startsWith(month+'-')&&a.professional===p.name&&a.status==='seen').length;rows+=`<tr><td><b>${esc(p.name)}</b><div class="email">${esc(p.email)}</div></td><td>${count}</td><td>${rate.toFixed(2)} €</td><td class="amount">${(count*rate).toFixed(2)} €</td></tr>`}$('donationTable').innerHTML=`<table class="donation-table"><thead><tr><th>Profesional</th><th>Pacientes vistos</th><th>Importe / visto</th><th>Donación del mes</th></tr></thead><tbody>${rows}</tbody></table>`}
function renderAll(){renderSchedule();renderProfessional();renderReports();renderDonations()}
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.view).classList.add('active');renderAll()});
$('prevWeek').onclick=()=>{weekOffset--;renderSchedule()};$('nextWeek').onclick=()=>{weekOffset++;renderSchedule()};$('todayWeek').onclick=()=>{weekOffset=0;renderSchedule()};$('jumpBtn').onclick=()=>{if(!$('jumpDate').value)return;const target=monday(parseDate($('jumpDate').value)),base=monday(new Date());weekOffset=Math.round((target-base)/(7*86400000));renderSchedule()};
$('assignBlockBtn').onclick=()=>{const d=monday(new Date(),weekOffset);openBlock(dateKey(d),'am')};$('blockType').onchange=toggleBlockType;$('blockRange').onchange=()=>{$('rangeFields').style.display=$('blockRange').checked?'block':'none'};$('saveBlockBtn').onclick=applyBlock;
$('bookingProfessional').onchange=toggleOther;$('saveBookingBtn').onclick=saveBooking;$('deleteBookingBtn').onclick=deleteBooking;document.querySelectorAll('#existingActions [data-status]').forEach(b=>b.onclick=()=>setStatus(b.dataset.status));
$('addPatientBtn').onclick=()=>patientDialog.showModal();$('savePatientBtn').onclick=addPatient;$('reportPrev').onclick=()=>{reportOffset--;renderReports()};$('reportNext').onclick=()=>{reportOffset++;renderReports()};$('reportCurrent').onclick=()=>{reportOffset=0;renderReports()};$('donationMonth').onchange=renderDonations;$('donationRate').onchange=()=>{data.donationRate=Math.max(0,Number($('donationRate').value||0));save()};
$('blockProfessional').innerHTML=PROFESSIONALS.map(p=>`<option>${p.name}</option>`).join('');$('bookingProfessional').innerHTML=PROFESSIONALS.map(p=>`<option>${p.name}</option>`).join('')+'<option>Otro</option>';$('weekdayGrid').innerHTML=[['L',1],['M',2],['X',3],['J',4],['V',5]].map(([n,v])=>`<label><input type="checkbox" value="${v}" checked> ${n}</label>`).join('');
renderAll();
