function renderSchedule(){const [m,f]=weekRange(weekOffset);$('weekLabel').textContent=`${fmtLong(m)} – ${fmtLong(f)}`;let out='';for(let i=0;i<5;i++){let d=new Date(m);d.setDate(m.getDate()+i);const dk=dateKey(d);out+=`<div class="day"><div class="day-head">${fmtDate(d)}</div>`;for(const sh of ['am','pm']){const b=data.blocks[blockKey(dk,sh)];let cls='',owner='Disponible',border='#b9c9cc';if(b?.type==='rented'){cls=' rented';owner='Alquilado';border='#7b8389'}else if(b?.type==='professional'){owner=b.professional;border=proByName(b.professional)?.color||'#0aaea7'}const range=sh==='am'?[8,15]:[15,22];out+=`<div class="block"><div class="block-head${cls}" style="border-left-color:${border}"><div><strong>${sh==='am'?'08:00–15:00':'15:00–22:00'}</strong><div class="block-owner">${esc(owner)}</div></div><button class="btn secondary small" onclick="openBlock('${dk}','${sh}')">Editar</button></div>`;for(let h=range[0];h<range[1];h++){const bk=bookingKey(dk,h),a=data.bookings[bk];let slotClass='',title='Disponible',detail='Haz clic para citar';if(b?.type==='rented'){slotClass=' rented';title='Alquilado';detail='Bloque externo'}else if(a){slotClass=a.status==='seen'?' seen':(a.status==='absence'||a.status==='cancelled')?' bad':' occupied';title=statusText(a.status);detail=`${esc(a.professional==='Otro'?(a.otherName||'Otro'):a.professional)} · ${esc(a.initials||'—')}`;}out+=`<div class="hour"><div class="time">${pad(h)}:00</div><div class="slot${slotClass}" onclick="openBooking('${dk}',${h})"><div class="slot-title">${title}</div><div class="slot-detail">${detail}</div>${a?`<span class="status ${a.status==='seen'?'seen':(a.status==='absence'||a.status==='cancelled')?'bad':'occupied'}">${statusText(a.status)}</span>`:''}</div></div>`}out+='</div>'}out+='</div>'}$('weekGrid').innerHTML=out}
function openBlock(date,shift){$('blockStart').value=date;$('blockShift').value=shift;$('blockRange').checked=false;$('rangeFields').style.display='none';$('blockEnd').value=date;const b=data.blocks[blockKey(date,shift)];$('blockType').value=b?.type||'professional';$('blockProfessional').value=b?.professional||PROFESSIONALS[0].name;toggleBlockType();blockDialog.showModal()}
function toggleBlockType(){$('blockProWrap').style.display=$('blockType').value==='professional'?'block':'none'}
function selectedWeekdays(){return [...document.querySelectorAll('#weekdayGrid input:checked')].map(x=>+x.value)}
function applyBlock(){const start=parseDate($('blockStart').value),end=$('blockRange').checked?parseDate($('blockEnd').value):start,shift=$('blockShift').value,type=$('blockType').value,days=selectedWeekdays();if(!$('blockStart').value)return;for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1)){if(d.getDay()===0||d.getDay()===6)continue;if($('blockRange').checked&&days.length&&!days.includes(d.getDay()))continue;const k=blockKey(dateKey(d),shift);if(type==='free')delete data.blocks[k];else if(type==='rented')data.blocks[k]={type:'rented'};else data.blocks[k]={type:'professional',professional:$('blockProfessional').value}}save();blockDialog.close()}
function openBooking(date,hour){currentSlot={date,hour};const b=data.blocks[blockKey(date,shiftForHour(hour))];$('bookingTitle').textContent=`${date} · ${pad(hour)}:00–${pad(hour+1)}:00`;const rented=b?.type==='rented';$('bookingRentedNotice').style.display=rented?'block':'none';$('bookingForm').style.display=rented?'none':'block';$('saveBookingBtn').style.display=rented?'none':'inline-block';$('deleteBookingBtn').style.display='none';if(rented){bookingDialog.showModal();return}const key=bookingKey(date,hour),a=data.bookings[key];const sel=$('bookingProfessional');sel.disabled=!!(b?.type==='professional');if(b?.type==='professional')sel.value=b.professional;else sel.value=a?.professional||PROFESSIONALS[0].name;$('otherName').value=a?.otherName||'';$('patientInitials').value=a?.initials||'';$('existingActions').style.display=a?'block':'none';$('deleteBookingBtn').style.display=a?'inline-block':'none';toggleOther();bookingDialog.showModal()}
function toggleOther(){$('otherNameWrap').style.display=$('bookingProfessional').value==='Otro'?'block':'none'}
function saveBooking(){if(!currentSlot)return;const professional=$('bookingProfessional').value,initials=$('patientInitials').value.trim().toUpperCase(),otherName=$('otherName').value.trim();if(professional==='Otro'){if(!otherName){alert('Escribe el nombre del profesional externo.');return}}else if(!initials){alert('Introduce las iniciales del paciente.');return}const k=bookingKey(currentSlot.date,currentSlot.hour),old=data.bookings[k];data.bookings[k]={professional,otherName:professional==='Otro'?otherName:'',initials,status:old?.status||'occupied'};save();bookingDialog.close()}
function setStatus(status){if(!currentSlot)return;const k=bookingKey(currentSlot.date,currentSlot.hour);if(data.bookings[k]){data.bookings[k].status=status;save();bookingDialog.close()}}
function deleteBooking(){if(!currentSlot)return;delete data.bookings[bookingKey(currentSlot.date,currentSlot.hour)];save();bookingDialog.close()}
